# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Alibaba Manage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Alibaba Manage
  pod 'AppCenter/Crashes', '~> 1.0.1'
  pod 'AppCenter/Analytics', '~> 1.0.1'
  pod 'AppCenterReactNativeShared', '~> 1.0.1'

  

  target 'Alibaba ManageTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Alibaba Manage-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Alibaba Manage-tvOS

  target 'Alibaba Manage-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
